### ISSUE TITLE
"Start new paragraph" should be reset after a line entry.

### ISSUE THREAD

**Issue by xuatz** [daryltanwk/ChatOrDie2#5]
To prevent accidental multiple new paragraph.

**Comment by daryltanwk** [comment]
would this backfire in future as people want to trigger "conversation mode" where characters have active dialog?

**Comment by xuatz** [comment]
You will need to decide which use-case is the more frequent 1. I believe that creating new paragraph should not be the default use-case.

**Comment by daryltanwk** [comment]
hmm, it isn't the default in the sense that when u just come in, it is off. But when u turn it on, should the app turn it back off or allow  you to go "conversation style" as i mentioned... i guess for now since the.........."community" prefers it to be off after each entry, i'll make it happen. 

#ListeningToThePeople

**Comment by xuatz** [comment]
"Do you hear the people sing? Singing the song of happy men!"
